/**
 * This class is generated by jOOQ
 */
package db.jooq;


import db.jooq.tables.Author;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in library
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table library.author
	 */
	public static final Author AUTHOR = db.jooq.tables.Author.AUTHOR;
}
