/**
 * This class is generated by jOOQ
 */
package cn.fyg.service.user.orm.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class App implements Serializable {

	private static final long serialVersionUID = 1562203044;

	private Long   id;
	private String name;
	private String remark;
	private String url;

	public App() {}

	public App(App value) {
		this.id = value.id;
		this.name = value.name;
		this.remark = value.remark;
		this.url = value.url;
	}

	public App(
		Long   id,
		String name,
		String remark,
		String url
	) {
		this.id = id;
		this.name = name;
		this.remark = remark;
		this.url = url;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
}
