/**
 * This class is generated by jOOQ
 */
package cn.fyg.service.user.orm.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Appuser implements Serializable {

	private static final long serialVersionUID = -732200487;

	private Long   id;
	private Long   appId;
	private Long   fyid;
	private String appinterid;

	public Appuser() {}

	public Appuser(Appuser value) {
		this.id = value.id;
		this.appId = value.appId;
		this.fyid = value.fyid;
		this.appinterid = value.appinterid;
	}

	public Appuser(
		Long   id,
		Long   appId,
		Long   fyid,
		String appinterid
	) {
		this.id = id;
		this.appId = appId;
		this.fyid = fyid;
		this.appinterid = appinterid;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getAppId() {
		return this.appId;
	}

	public void setAppId(Long appId) {
		this.appId = appId;
	}

	public Long getFyid() {
		return this.fyid;
	}

	public void setFyid(Long fyid) {
		this.fyid = fyid;
	}

	public String getAppinterid() {
		return this.appinterid;
	}

	public void setAppinterid(String appinterid) {
		this.appinterid = appinterid;
	}
}
