/**
 * This class is generated by jOOQ
 */
package cn.fyg.service.user.orm.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

	private static final long serialVersionUID = -1442524186;

	private Long   fyid;
	private String uname;
	private String uemail;
	private String uphone;
	private String password;
	private String realname;
	private String state;
	private Long   createtime;

	public User() {}

	public User(User value) {
		this.fyid = value.fyid;
		this.uname = value.uname;
		this.uemail = value.uemail;
		this.uphone = value.uphone;
		this.password = value.password;
		this.realname = value.realname;
		this.state = value.state;
		this.createtime = value.createtime;
	}

	public User(
		Long   fyid,
		String uname,
		String uemail,
		String uphone,
		String password,
		String realname,
		String state,
		Long   createtime
	) {
		this.fyid = fyid;
		this.uname = uname;
		this.uemail = uemail;
		this.uphone = uphone;
		this.password = password;
		this.realname = realname;
		this.state = state;
		this.createtime = createtime;
	}

	public Long getFyid() {
		return this.fyid;
	}

	public void setFyid(Long fyid) {
		this.fyid = fyid;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getUemail() {
		return this.uemail;
	}

	public void setUemail(String uemail) {
		this.uemail = uemail;
	}

	public String getUphone() {
		return this.uphone;
	}

	public void setUphone(String uphone) {
		this.uphone = uphone;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Long getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Long createtime) {
		this.createtime = createtime;
	}
}
