/**
 * This class is generated by jOOQ
 */
package cn.fyg.service.user.orm.jooq.tables.daos;


import cn.fyg.service.user.orm.jooq.tables.User;
import cn.fyg.service.user.orm.jooq.tables.records.UserRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDao extends DAOImpl<UserRecord, cn.fyg.service.user.orm.jooq.tables.pojos.User, Long> {

	/**
	 * Create a new UserDao without any configuration
	 */
	public UserDao() {
		super(User.USER, cn.fyg.service.user.orm.jooq.tables.pojos.User.class);
	}

	/**
	 * Create a new UserDao with an attached configuration
	 */
	public UserDao(Configuration configuration) {
		super(User.USER, cn.fyg.service.user.orm.jooq.tables.pojos.User.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Long getId(cn.fyg.service.user.orm.jooq.tables.pojos.User object) {
		return object.getFyid();
	}

	/**
	 * Fetch records that have <code>fyid IN (values)</code>
	 */
	public List<cn.fyg.service.user.orm.jooq.tables.pojos.User> fetchByFyid(Long... values) {
		return fetch(User.USER.FYID, values);
	}

	/**
	 * Fetch a unique record that has <code>fyid = value</code>
	 */
	public cn.fyg.service.user.orm.jooq.tables.pojos.User fetchOneByFyid(Long value) {
		return fetchOne(User.USER.FYID, value);
	}

	/**
	 * Fetch records that have <code>uname IN (values)</code>
	 */
	public List<cn.fyg.service.user.orm.jooq.tables.pojos.User> fetchByUname(String... values) {
		return fetch(User.USER.UNAME, values);
	}

	/**
	 * Fetch records that have <code>uemail IN (values)</code>
	 */
	public List<cn.fyg.service.user.orm.jooq.tables.pojos.User> fetchByUemail(String... values) {
		return fetch(User.USER.UEMAIL, values);
	}

	/**
	 * Fetch records that have <code>uphone IN (values)</code>
	 */
	public List<cn.fyg.service.user.orm.jooq.tables.pojos.User> fetchByUphone(String... values) {
		return fetch(User.USER.UPHONE, values);
	}

	/**
	 * Fetch records that have <code>password IN (values)</code>
	 */
	public List<cn.fyg.service.user.orm.jooq.tables.pojos.User> fetchByPassword(String... values) {
		return fetch(User.USER.PASSWORD, values);
	}

	/**
	 * Fetch records that have <code>realname IN (values)</code>
	 */
	public List<cn.fyg.service.user.orm.jooq.tables.pojos.User> fetchByRealname(String... values) {
		return fetch(User.USER.REALNAME, values);
	}

	/**
	 * Fetch records that have <code>state IN (values)</code>
	 */
	public List<cn.fyg.service.user.orm.jooq.tables.pojos.User> fetchByState(String... values) {
		return fetch(User.USER.STATE, values);
	}

	/**
	 * Fetch records that have <code>createtime IN (values)</code>
	 */
	public List<cn.fyg.service.user.orm.jooq.tables.pojos.User> fetchByCreatetime(Long... values) {
		return fetch(User.USER.CREATETIME, values);
	}
}
