/**
 * This class is generated by jOOQ
 */
package db.jooq.tables.daos;


import db.jooq.tables.Author;
import db.jooq.tables.records.AuthorRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorDao extends DAOImpl<AuthorRecord, db.jooq.tables.pojos.Author, Integer> {

	/**
	 * Create a new AuthorDao without any configuration
	 */
	public AuthorDao() {
		super(Author.AUTHOR, db.jooq.tables.pojos.Author.class);
	}

	/**
	 * Create a new AuthorDao with an attached configuration
	 */
	public AuthorDao(Configuration configuration) {
		super(Author.AUTHOR, db.jooq.tables.pojos.Author.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(db.jooq.tables.pojos.Author object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<db.jooq.tables.pojos.Author> fetchById(Integer... values) {
		return fetch(Author.AUTHOR.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public db.jooq.tables.pojos.Author fetchOneById(Integer value) {
		return fetchOne(Author.AUTHOR.ID, value);
	}

	/**
	 * Fetch records that have <code>first_name IN (values)</code>
	 */
	public List<db.jooq.tables.pojos.Author> fetchByFirstName(String... values) {
		return fetch(Author.AUTHOR.FIRST_NAME, values);
	}

	/**
	 * Fetch records that have <code>last_name IN (values)</code>
	 */
	public List<db.jooq.tables.pojos.Author> fetchByLastName(String... values) {
		return fetch(Author.AUTHOR.LAST_NAME, values);
	}
}
