/**
 * This class is generated by jOOQ
 */
package cn.fyg.service.user.orm.jooq.tables;


import cn.fyg.service.user.orm.jooq.Keys;
import cn.fyg.service.user.orm.jooq.Service_user_dev;
import cn.fyg.service.user.orm.jooq.tables.records.AppRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class App extends TableImpl<AppRecord> {

	private static final long serialVersionUID = -1834283414;

	/**
	 * The reference instance of <code>service-user-dev.app</code>
	 */
	public static final App APP = new App();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AppRecord> getRecordType() {
		return AppRecord.class;
	}

	/**
	 * The column <code>service-user-dev.app.id</code>.
	 */
	public final TableField<AppRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>service-user-dev.app.name</code>.
	 */
	public final TableField<AppRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>service-user-dev.app.remark</code>.
	 */
	public final TableField<AppRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>service-user-dev.app.url</code>.
	 */
	public final TableField<AppRecord, String> URL = createField("url", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * Create a <code>service-user-dev.app</code> table reference
	 */
	public App() {
		this("app", null);
	}

	/**
	 * Create an aliased <code>service-user-dev.app</code> table reference
	 */
	public App(String alias) {
		this(alias, APP);
	}

	private App(String alias, Table<AppRecord> aliased) {
		this(alias, aliased, null);
	}

	private App(String alias, Table<AppRecord> aliased, Field<?>[] parameters) {
		super(alias, Service_user_dev.SERVICE_USER_DEV, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<AppRecord, Long> getIdentity() {
		return Keys.IDENTITY_APP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AppRecord> getPrimaryKey() {
		return Keys.KEY_APP_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AppRecord>> getKeys() {
		return Arrays.<UniqueKey<AppRecord>>asList(Keys.KEY_APP_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public App as(String alias) {
		return new App(alias, this);
	}

	/**
	 * Rename this table
	 */
	public App rename(String name) {
		return new App(name, null);
	}
}
