/**
 * This class is generated by jOOQ
 */
package cn.fyg.service.user.orm.jooq;


import cn.fyg.service.user.orm.jooq.tables.App;
import cn.fyg.service.user.orm.jooq.tables.Appuser;
import cn.fyg.service.user.orm.jooq.tables.User;
import cn.fyg.service.user.orm.jooq.tables.records.AppRecord;
import cn.fyg.service.user.orm.jooq.tables.records.AppuserRecord;
import cn.fyg.service.user.orm.jooq.tables.records.UserRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>service-user-dev</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<AppRecord, Long> IDENTITY_APP = Identities0.IDENTITY_APP;
	public static final Identity<AppuserRecord, Long> IDENTITY_APPUSER = Identities0.IDENTITY_APPUSER;
	public static final Identity<UserRecord, Long> IDENTITY_USER = Identities0.IDENTITY_USER;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<AppRecord> KEY_APP_PRIMARY = UniqueKeys0.KEY_APP_PRIMARY;
	public static final UniqueKey<AppuserRecord> KEY_APPUSER_PRIMARY = UniqueKeys0.KEY_APPUSER_PRIMARY;
	public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final ForeignKey<AppuserRecord, AppRecord> APPUSER_3aAPP_ID = ForeignKeys0.APPUSER_3aAPP_ID;
	public static final ForeignKey<AppuserRecord, UserRecord> APPUSER_3aFYID = ForeignKeys0.APPUSER_3aFYID;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends AbstractKeys {
		public static Identity<AppRecord, Long> IDENTITY_APP = createIdentity(App.APP, App.APP.ID);
		public static Identity<AppuserRecord, Long> IDENTITY_APPUSER = createIdentity(Appuser.APPUSER, Appuser.APPUSER.ID);
		public static Identity<UserRecord, Long> IDENTITY_USER = createIdentity(User.USER, User.USER.FYID);
	}

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<AppRecord> KEY_APP_PRIMARY = createUniqueKey(App.APP, App.APP.ID);
		public static final UniqueKey<AppuserRecord> KEY_APPUSER_PRIMARY = createUniqueKey(Appuser.APPUSER, Appuser.APPUSER.ID);
		public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = createUniqueKey(User.USER, User.USER.FYID);
	}

	private static class ForeignKeys0 extends AbstractKeys {
		public static final ForeignKey<AppuserRecord, AppRecord> APPUSER_3aAPP_ID = createForeignKey(cn.fyg.service.user.orm.jooq.Keys.KEY_APP_PRIMARY, Appuser.APPUSER, Appuser.APPUSER.APP_ID);
		public static final ForeignKey<AppuserRecord, UserRecord> APPUSER_3aFYID = createForeignKey(cn.fyg.service.user.orm.jooq.Keys.KEY_USER_PRIMARY, Appuser.APPUSER, Appuser.APPUSER.FYID);
	}
}
