/**
 * This class is generated by jOOQ
 */
package cn.fyg.service.user.orm.jooq;


import cn.fyg.service.user.orm.jooq.tables.App;
import cn.fyg.service.user.orm.jooq.tables.Appuser;
import cn.fyg.service.user.orm.jooq.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in service-user-dev
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table service-user-dev.app
	 */
	public static final App APP = cn.fyg.service.user.orm.jooq.tables.App.APP;

	/**
	 * The table service-user-dev.appuser
	 */
	public static final Appuser APPUSER = cn.fyg.service.user.orm.jooq.tables.Appuser.APPUSER;

	/**
	 * The table service-user-dev.user
	 */
	public static final User USER = cn.fyg.service.user.orm.jooq.tables.User.USER;
}
