/**
 * This class is generated by jOOQ
 */
package cn.fyg.service.user.orm.jooq.tables.records;


import cn.fyg.service.user.orm.jooq.tables.Appuser;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppuserRecord extends UpdatableRecordImpl<AppuserRecord> implements Record4<Long, Long, Long, String> {

	private static final long serialVersionUID = 1733907260;

	/**
	 * Setter for <code>service-user-dev.appuser.id</code>.
	 */
	public void setId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>service-user-dev.appuser.id</code>.
	 */
	public Long getId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>service-user-dev.appuser.app_id</code>.
	 */
	public void setAppId(Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>service-user-dev.appuser.app_id</code>.
	 */
	public Long getAppId() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>service-user-dev.appuser.fyid</code>.
	 */
	public void setFyid(Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>service-user-dev.appuser.fyid</code>.
	 */
	public Long getFyid() {
		return (Long) getValue(2);
	}

	/**
	 * Setter for <code>service-user-dev.appuser.appinterid</code>.
	 */
	public void setAppinterid(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>service-user-dev.appuser.appinterid</code>.
	 */
	public String getAppinterid() {
		return (String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Long, Long, Long, String> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Long, Long, Long, String> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return Appuser.APPUSER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return Appuser.APPUSER.APP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field3() {
		return Appuser.APPUSER.FYID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Appuser.APPUSER.APPINTERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getAppId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value3() {
		return getFyid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getAppinterid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppuserRecord value1(Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppuserRecord value2(Long value) {
		setAppId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppuserRecord value3(Long value) {
		setFyid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppuserRecord value4(String value) {
		setAppinterid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppuserRecord values(Long value1, Long value2, Long value3, String value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AppuserRecord
	 */
	public AppuserRecord() {
		super(Appuser.APPUSER);
	}

	/**
	 * Create a detached, initialised AppuserRecord
	 */
	public AppuserRecord(Long id, Long appId, Long fyid, String appinterid) {
		super(Appuser.APPUSER);

		setValue(0, id);
		setValue(1, appId);
		setValue(2, fyid);
		setValue(3, appinterid);
	}
}
