/**
 * This class is generated by jOOQ
 */
package cn.fyg.service.user.orm.jooq.tables.records;


import cn.fyg.service.user.orm.jooq.tables.User;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record8<Long, String, String, String, String, String, String, Long> {

	private static final long serialVersionUID = 845876601;

	/**
	 * Setter for <code>service-user-dev.user.fyid</code>.
	 */
	public void setFyid(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>service-user-dev.user.fyid</code>.
	 */
	public Long getFyid() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>service-user-dev.user.uname</code>.
	 */
	public void setUname(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>service-user-dev.user.uname</code>.
	 */
	public String getUname() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>service-user-dev.user.uemail</code>.
	 */
	public void setUemail(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>service-user-dev.user.uemail</code>.
	 */
	public String getUemail() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>service-user-dev.user.uphone</code>.
	 */
	public void setUphone(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>service-user-dev.user.uphone</code>.
	 */
	public String getUphone() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>service-user-dev.user.password</code>.
	 */
	public void setPassword(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>service-user-dev.user.password</code>.
	 */
	public String getPassword() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>service-user-dev.user.realname</code>.
	 */
	public void setRealname(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>service-user-dev.user.realname</code>.
	 */
	public String getRealname() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>service-user-dev.user.state</code>.
	 */
	public void setState(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>service-user-dev.user.state</code>.
	 */
	public String getState() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>service-user-dev.user.createtime</code>.
	 */
	public void setCreatetime(Long value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>service-user-dev.user.createtime</code>.
	 */
	public Long getCreatetime() {
		return (Long) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Long, String, String, String, String, String, String, Long> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Long, String, String, String, String, String, String, Long> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return User.USER.FYID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return User.USER.UNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return User.USER.UEMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return User.USER.UPHONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return User.USER.PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return User.USER.REALNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return User.USER.STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field8() {
		return User.USER.CREATETIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getFyid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getUname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getUemail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getUphone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getRealname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value8() {
		return getCreatetime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value1(Long value) {
		setFyid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value2(String value) {
		setUname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value3(String value) {
		setUemail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value4(String value) {
		setUphone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value5(String value) {
		setPassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value6(String value) {
		setRealname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value7(String value) {
		setState(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value8(Long value) {
		setCreatetime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, Long value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserRecord
	 */
	public UserRecord() {
		super(User.USER);
	}

	/**
	 * Create a detached, initialised UserRecord
	 */
	public UserRecord(Long fyid, String uname, String uemail, String uphone, String password, String realname, String state, Long createtime) {
		super(User.USER);

		setValue(0, fyid);
		setValue(1, uname);
		setValue(2, uemail);
		setValue(3, uphone);
		setValue(4, password);
		setValue(5, realname);
		setValue(6, state);
		setValue(7, createtime);
	}
}
